cat copy_ansible.yaml 
- name: Copy text files to Appservers
  hosts: all
  become: yes
  tasks:
    - name: Copy blog.txt to stapp01
      ansible.builtin.copy:
        src: /usr/src/itadmin/blog.txt
        dest: /opt/itadmin/
        owner: tony
        group: tony
        mode: "0744"
      when: inventory_hostname == "stapp01"
    - name: Copy story.txt to stapp02
      ansible.builtin.copy:
        src: /usr/src/itadmin/story.txt
        dest: /opt/itadmin/
        owner: steve
        group: steve
        mode: "0744"
      when: inventory_hostname == "stapp02"
    - name: Copy media.txt to stapp03
      ansible.builtin.copy:
        src: /usr/src/itadmin/media.txt
        dest: /opt/itadmin/
        owner: banner
        group: banner
        mode: "0744"
      when: inventory_hostname == "stapp03
